### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by shahmirzali49** [shoyabsiddique/youtube_video_player#2]
```
PotraitPlayer(
                link: 'www.youtube.com/watch?v=j_1eLgCut8Q',
                aspectRatio: 16 / 9, // Adjust the aspect ratio as needed
                kColorWhite: Colors.white, // Optional: Customize color themes
                kColorPrimary: Colors.orange,
                kColorBlack: Colors.black,
              ),
```

**Comment by shahmirzali49** [comment]
Logs:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      WakelockApi.toggle (package:wakelock_platform_interface/messages.dart:89:7)
<asynchronous suspension>
#1      MethodChannelWakelock.toggle (package:wakelock_platform_interface/method_channel_wakelock.dart:20:5)
<asynchronous suspension>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      AVFoundationVideoPlayerApi.initialize (package:video_player_avfoundation/src/messages.g.dart:283:7)
<asynchronous suspension>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      AVFoundationVideoPlayerApi.setMixWithOthers (package:video_player_avfoundation/src/messages.g.dart:523:7)
<asynchronous suspension>
#1      VideoPlayerController.initialize (package:video_player/video_player.dart:430:7)
<asynchronous suspension>
#2      VideoPlayerSreenController.onInit.<anonymous closure> (package:youtube_video_player/video_player_controller.dart:86:26)
<asynchronous suspension>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getScreenBrightness on channel github.com/aaassseee/screen_brightness)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
<asynchronous suspension>
#1      MethodChannelScreenBrightness.current (package:screen_brightness_platform_interface/method_channel_screen_brightness.dart:66:31)
<asynchronous suspension>
#2      VideoPlayerSreenController.onInit.<anonymous closure> (package:youtube_video_player/video_player_controller.dart:102:15)
<asynchronous suspension>
```

**Comment by shoyabsiddique** [comment]
check the current version and lemme know
