### ISSUE TITLE
Not Working on Windows

### ISSUE THREAD

**Issue by mohgit97** [shoyabsiddique/youtube_video_player#6]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: UnimplementedError: init() has not been implemented.
#0      VideoPlayerPlatform.init (package:video_player_platform_interface/video_player_platform_interface.dart:43:5)
#1      _videoPlayerPlatform (package:video_player/video_player.dart:28:21)
#2      VideoPlayerController.initialize (package:video_player/video_player.dart:415:13)
#3      VideoPlayerSreenController.onInit (package:youtube_video_player/video_player_controller.dart:122:8)
<asynchronous suspension>

**Comment by shoyabsiddique** [comment]
will look into it and let you know

**Comment by mohgit97** [comment]
Any news?

**Comment by Mohammad-Areeb-Kashaf** [comment]
There is currently no implementation for the youtube player in windows. In fact, webview_flutter package does not support windows yet. So, I think If you want to implement it in windows. You will have to wait till webview_flutter supports it.

**Comment by mohgit97** [comment]
but your package depends on video_player not on flutter_webview

**Comment by Mohammad-Areeb-Kashaf** [comment]
> but your package depends on video_player not on flutter_webview

I just want to say that currently windows is not stable with flutter and you should wait for flutter team to extend its support further which will some how result in more packages supporting windows and implementing for it. BTW It's not my package I am also user of this package and I just wanted to let you know that you won't be able to use it for windows. as I was also not able to do so.

**Comment by mohgit97** [comment]
> > but your package depends on video_player not on flutter_webview
> 
> I just want to say that currently windows is not stable with flutter and you should wait for flutter team to extend its support further which will some how result in more packages supporting windows and implementing for it. BTW It's not my package I am also user of this package and I just wanted to let you know that you won't be able to use it for windows. as I was also not able to do so.

i am using it with video_palyer_win package but it have problem in disposing the controller when you open new video
